/*
 * IDENTIFICATION:
 * stub generated Sat Jul 14 23:00:47 2012
 * with a MiG generated by bootstrap_cmds-84
 * OPTIONS: 
 */

/* Module DSlibinfoMIG */

#define	__MIG_check__Request__DSlibinfoMIG_subsystem__ 1

#include <string.h>
#include <mach/ndr.h>
#include <mach/boolean.h>
#include <mach/kern_return.h>
#include <mach/notify.h>
#include <mach/mach_types.h>
#include <mach/message.h>
#include <mach/mig_errors.h>
#include <mach/port.h>

#include <sys/types.h>
#include <mach/std_types.h>
#include <mach/mig.h>
#include <mach/mig.h>
#include <mach/mach_types.h>
#include "DSlibinfoMIG_types.h"

#ifndef	mig_internal
#define	mig_internal	static __inline__
#endif	/* mig_internal */

#ifndef	mig_external
#define mig_external
#endif	/* mig_external */

#if	!defined(__MigTypeCheck) && defined(TypeCheck)
#define	__MigTypeCheck		TypeCheck	/* Legacy setting */
#endif	/* !defined(__MigTypeCheck) */

#if	!defined(__MigKernelSpecificCode) && defined(_MIG_KERNEL_SPECIFIC_CODE_)
#define	__MigKernelSpecificCode	_MIG_KERNEL_SPECIFIC_CODE_	/* Legacy setting */
#endif	/* !defined(__MigKernelSpecificCode) */

#ifndef	LimitCheck
#define	LimitCheck 0
#endif	/* LimitCheck */

#ifndef	min
#define	min(a,b)  ( ((a) < (b))? (a): (b) )
#endif	/* min */

#if !defined(_WALIGN_)
#define _WALIGN_(x) (((x) + 3) & ~3)
#endif /* !defined(_WALIGN_) */

#if !defined(_WALIGNSZ_)
#define _WALIGNSZ_(x) _WALIGN_(sizeof(x))
#endif /* !defined(_WALIGNSZ_) */

#ifndef	UseStaticTemplates
#define	UseStaticTemplates	0
#endif	/* UseStaticTemplates */

#ifndef	__DeclareRcvRpc
#define	__DeclareRcvRpc(_NUM_, _NAME_)
#endif	/* __DeclareRcvRpc */

#ifndef	__BeforeRcvRpc
#define	__BeforeRcvRpc(_NUM_, _NAME_)
#endif	/* __BeforeRcvRpc */

#ifndef	__AfterRcvRpc
#define	__AfterRcvRpc(_NUM_, _NAME_)
#endif	/* __AfterRcvRpc */

#ifndef	__DeclareRcvSimple
#define	__DeclareRcvSimple(_NUM_, _NAME_)
#endif	/* __DeclareRcvSimple */

#ifndef	__BeforeRcvSimple
#define	__BeforeRcvSimple(_NUM_, _NAME_)
#endif	/* __BeforeRcvSimple */

#ifndef	__AfterRcvSimple
#define	__AfterRcvSimple(_NUM_, _NAME_)
#endif	/* __AfterRcvSimple */

#define novalue void

#define msgh_request_port	msgh_local_port
#define MACH_MSGH_BITS_REQUEST(bits)	MACH_MSGH_BITS_LOCAL(bits)
#define msgh_reply_port		msgh_remote_port
#define MACH_MSGH_BITS_REPLY(bits)	MACH_MSGH_BITS_REMOTE(bits)

#define MIG_RETURN_ERROR(X, code)	{\
				((mig_reply_error_t *)X)->RetCode = code;\
				((mig_reply_error_t *)X)->NDR = NDR_record;\
				return;\
				}

/* typedefs for all requests */

#ifndef __Request__DSlibinfoMIG_subsystem__defined
#define __Request__DSlibinfoMIG_subsystem__defined

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		mach_msg_type_number_t nameOffset; /* MiG doesn't use it */
		mach_msg_type_number_t nameCnt;
		char name[256];
	} __Request__GetProcedureNumber_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		int32_t proc;
		mach_msg_type_number_t requestCnt;
		char request[16384];
	} __Request__Query_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t replyToPort;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		int32_t proc;
		mach_msg_type_number_t requestCnt;
		char request[16384];
		mach_vm_address_t callbackAddr;
	} __Request__Query_async_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif
#endif /* !__Request__DSlibinfoMIG_subsystem__defined */

/* typedefs for all replies */

#ifndef __Reply__DSlibinfoMIG_subsystem__defined
#define __Reply__DSlibinfoMIG_subsystem__defined

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
		int32_t procno;
	} __Reply__GetProcedureNumber_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_ool_descriptor_t ooreply;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		mach_msg_type_number_t replyCnt;
		char reply[16384];
		mach_msg_type_number_t ooreplyCnt;
	} __Reply__Query_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply__Query_async_t;
#ifdef  __MigPackStructs
#pragma pack()
#endif
#endif /* !__Reply__DSlibinfoMIG_subsystem__defined */


/* union of all replies */

#ifndef __ReplyUnion__libinfoDSmig_do_DSlibinfoMIG_subsystem__defined
#define __ReplyUnion__libinfoDSmig_do_DSlibinfoMIG_subsystem__defined
union __ReplyUnion__libinfoDSmig_do_DSlibinfoMIG_subsystem {
	__Reply__GetProcedureNumber_t Reply_GetProcedureNumber;
	__Reply__Query_t Reply_Query;
	__Reply__Query_async_t Reply_Query_async;
};
#endif /* __RequestUnion__libinfoDSmig_do_DSlibinfoMIG_subsystem__defined */
/* Forward Declarations */


mig_internal novalue _XGetProcedureNumber
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _XQuery
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _XQuery_async
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);


#if ( __MigTypeCheck )
#if __MIG_check__Request__DSlibinfoMIG_subsystem__
#if !defined(__MIG_check__Request__GetProcedureNumber_t__defined)
#define __MIG_check__Request__GetProcedureNumber_t__defined

mig_internal kern_return_t __MIG_check__Request__GetProcedureNumber_t(__attribute__((__unused__)) __Request__GetProcedureNumber_t *In0P)
{

	typedef __Request__GetProcedureNumber_t __Request;
#if	__MigTypeCheck
	unsigned int msgh_size;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	msgh_size = In0P->Head.msgh_size;
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 256)) ||  (msgh_size > (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if defined(__NDR_convert__int_rep__Request__GetProcedureNumber_t__nameCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__GetProcedureNumber_t__nameCnt(&In0P->nameCnt, In0P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__GetProcedureNumber_t__nameCnt__defined */
#if	__MigTypeCheck
	if ( In0P->nameCnt > 256 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 256)) < In0P->nameCnt) ||
	    (msgh_size != (mach_msg_size_t)(sizeof(__Request) - 256) + _WALIGN_(In0P->nameCnt)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	{
		char * msg_limit = ((char *) In0P) + In0P->Head.msgh_size;
		size_t memchr_limit;

		memchr_limit = min((msg_limit - In0P->name),  256);
		if (( memchr(In0P->name, '\0', memchr_limit) == NULL ))
			return MIG_BAD_ARGUMENTS; // string length exceeds buffer length!
	}
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__GetProcedureNumber_t__defined) */
#endif /* __MIG_check__Request__DSlibinfoMIG_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine GetProcedureNumber */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t libinfoDSmig_do_GetProcedureNumber
(
	mach_port_t server,
	proc_name_t name,
	int32_t *procno,
	audit_token_t bsmtoken
);

/* Routine GetProcedureNumber */
mig_internal novalue _XGetProcedureNumber
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		mach_msg_type_number_t nameOffset; /* MiG doesn't use it */
		mach_msg_type_number_t nameCnt;
		char name[256];
		mach_msg_max_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__GetProcedureNumber_t __Request;
	typedef __Reply__GetProcedureNumber_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
	mach_msg_max_trailer_t *TrailerP;
#if	__MigTypeCheck
	unsigned int trailer_size;
#endif	/* __MigTypeCheck */
#ifdef	__MIG_check__Request__GetProcedureNumber_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__GetProcedureNumber_t__defined */

	__DeclareRcvRpc(50000, "GetProcedureNumber")
	__BeforeRcvRpc(50000, "GetProcedureNumber")

#if	defined(__MIG_check__Request__GetProcedureNumber_t__defined)
	check_result = __MIG_check__Request__GetProcedureNumber_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__GetProcedureNumber_t__defined) */

	TrailerP = (mach_msg_max_trailer_t *)((vm_offset_t)In0P +
		round_msg(In0P->Head.msgh_size));
	if (TrailerP->msgh_trailer_type != MACH_MSG_TRAILER_FORMAT_0)
		{ MIG_RETURN_ERROR(In0P, MIG_TRAILER_ERROR); }
#if	__MigTypeCheck
	trailer_size = TrailerP->msgh_trailer_size -
		(mach_msg_size_t)(sizeof(mach_msg_trailer_type_t) - sizeof(mach_msg_trailer_size_t));
#endif	/* __MigTypeCheck */
#if	__MigTypeCheck
	if (trailer_size < (mach_msg_size_t)sizeof(audit_token_t))
		{ MIG_RETURN_ERROR(OutP, MIG_TRAILER_ERROR); }
	trailer_size -= (mach_msg_size_t)sizeof(audit_token_t);
#endif	/* __MigTypeCheck */
	OutP->RetCode = libinfoDSmig_do_GetProcedureNumber(In0P->Head.msgh_request_port, In0P->name, &OutP->procno, TrailerP->msgh_audit);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}

	OutP->NDR = NDR_record;


	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	__AfterRcvRpc(50000, "GetProcedureNumber")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__DSlibinfoMIG_subsystem__
#if !defined(__MIG_check__Request__Query_t__defined)
#define __MIG_check__Request__Query_t__defined

mig_internal kern_return_t __MIG_check__Request__Query_t(__attribute__((__unused__)) __Request__Query_t *In0P)
{

	typedef __Request__Query_t __Request;
#if	__MigTypeCheck
	unsigned int msgh_size;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	msgh_size = In0P->Head.msgh_size;
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 16384)) ||  (msgh_size > (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if defined(__NDR_convert__int_rep__Request__Query_t__requestCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__Query_t__requestCnt(&In0P->requestCnt, In0P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__Query_t__requestCnt__defined */
#if	__MigTypeCheck
	if ( In0P->requestCnt > 16384 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 16384)) < In0P->requestCnt) ||
	    (msgh_size != (mach_msg_size_t)(sizeof(__Request) - 16384) + _WALIGN_(In0P->requestCnt)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__Query_t__defined) */
#endif /* __MIG_check__Request__DSlibinfoMIG_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine Query */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t libinfoDSmig_do_Query
(
	mach_port_t server,
	int32_t proc,
	inline_data_t request,
	mach_msg_type_number_t requestCnt,
	inline_data_t reply,
	mach_msg_type_number_t *replyCnt,
	vm_offset_t *ooreply,
	mach_msg_type_number_t *ooreplyCnt,
	audit_token_t bsmtoken
);

/* Routine Query */
mig_internal novalue _XQuery
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		int32_t proc;
		mach_msg_type_number_t requestCnt;
		char request[16384];
		mach_msg_max_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__Query_t __Request;
	typedef __Reply__Query_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
	unsigned int msgh_size_delta;

	mach_msg_max_trailer_t *TrailerP;
#if	__MigTypeCheck
	unsigned int trailer_size;
#endif	/* __MigTypeCheck */
#ifdef	__MIG_check__Request__Query_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__Query_t__defined */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t ooreplyTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		TRUE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	mach_msg_type_number_t ooreplyCnt;

	__DeclareRcvRpc(50001, "Query")
	__BeforeRcvRpc(50001, "Query")

#if	defined(__MIG_check__Request__Query_t__defined)
	check_result = __MIG_check__Request__Query_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__Query_t__defined) */

	TrailerP = (mach_msg_max_trailer_t *)((vm_offset_t)In0P +
		round_msg(In0P->Head.msgh_size));
	if (TrailerP->msgh_trailer_type != MACH_MSG_TRAILER_FORMAT_0)
		{ MIG_RETURN_ERROR(In0P, MIG_TRAILER_ERROR); }
#if	__MigTypeCheck
	trailer_size = TrailerP->msgh_trailer_size -
		(mach_msg_size_t)(sizeof(mach_msg_trailer_type_t) - sizeof(mach_msg_trailer_size_t));
#endif	/* __MigTypeCheck */
#if	__MigTypeCheck
	if (trailer_size < (mach_msg_size_t)sizeof(audit_token_t))
		{ MIG_RETURN_ERROR(OutP, MIG_TRAILER_ERROR); }
	trailer_size -= (mach_msg_size_t)sizeof(audit_token_t);
#endif	/* __MigTypeCheck */
#if	UseStaticTemplates
	OutP->ooreply = ooreplyTemplate;
#else	/* UseStaticTemplates */
	OutP->ooreply.deallocate =  TRUE;
	OutP->ooreply.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->ooreply.type = MACH_MSG_OOL_DESCRIPTOR;
#endif	/* UseStaticTemplates */


	OutP->replyCnt = 16384;

	RetCode = libinfoDSmig_do_Query(In0P->Head.msgh_request_port, In0P->proc, In0P->request, In0P->requestCnt, OutP->reply, &OutP->replyCnt, (vm_offset_t *)&(OutP->ooreply.address), &ooreplyCnt, TrailerP->msgh_audit);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}
	OutP->ooreply.size = ooreplyCnt;


	OutP->NDR = NDR_record;

	msgh_size_delta = _WALIGN_((OutP->replyCnt + 3) & ~3);
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply) - 16384) + msgh_size_delta;
	OutP = (Reply *) ((pointer_t) OutP + msgh_size_delta - 16384);
	OutP->ooreplyCnt = ooreplyCnt;

	OutP = (Reply *) OutHeadP;
	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(50001, "Query")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__DSlibinfoMIG_subsystem__
#if !defined(__MIG_check__Request__Query_async_t__defined)
#define __MIG_check__Request__Query_async_t__defined

mig_internal kern_return_t __MIG_check__Request__Query_async_t(__attribute__((__unused__)) __Request__Query_async_t *In0P, __attribute__((__unused__)) __Request__Query_async_t **In1PP)
{

	typedef __Request__Query_async_t __Request;
	__Request *In1P;
#if	__MigTypeCheck
	unsigned int msgh_size;
#endif	/* __MigTypeCheck */
	unsigned int msgh_size_delta;

#if	__MigTypeCheck
	msgh_size = In0P->Head.msgh_size;
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 1) ||
	    (msgh_size < (mach_msg_size_t)(sizeof(__Request) - 16384)) ||  (msgh_size > (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->replyToPort.type != MACH_MSG_PORT_DESCRIPTOR ||
	    In0P->replyToPort.disposition != 18)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if defined(__NDR_convert__int_rep__Request__Query_async_t__requestCnt__defined)
	if (In0P->NDR.int_rep != NDR_record.int_rep)
		__NDR_convert__int_rep__Request__Query_async_t__requestCnt(&In0P->requestCnt, In0P->NDR.int_rep);
#endif	/* __NDR_convert__int_rep__Request__Query_async_t__requestCnt__defined */
	msgh_size_delta = _WALIGN_(In0P->requestCnt);
#if	__MigTypeCheck
	if ( In0P->requestCnt > 16384 )
		return MIG_BAD_ARGUMENTS;
	if (((msgh_size - (mach_msg_size_t)(sizeof(__Request) - 16384)) < In0P->requestCnt) ||
	    (msgh_size != (mach_msg_size_t)(sizeof(__Request) - 16384) + _WALIGN_(In0P->requestCnt)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	*In1PP = In1P = (__Request *) ((pointer_t) In0P + msgh_size_delta - 16384);

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__Query_async_t__defined) */
#endif /* __MIG_check__Request__DSlibinfoMIG_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* SimpleRoutine Query_async */
#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
kern_return_t libinfoDSmig_do_Query_async
(
	mach_port_t server,
	mach_port_t replyToPort,
	int32_t proc,
	inline_data_t request,
	mach_msg_type_number_t requestCnt,
	mach_vm_address_t callbackAddr,
	audit_token_t bsmtoken
);

/* SimpleRoutine Query_async */
mig_internal novalue _XQuery_async
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t replyToPort;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		int32_t proc;
		mach_msg_type_number_t requestCnt;
		char request[16384];
		mach_vm_address_t callbackAddr;
		mach_msg_max_trailer_t trailer;
	} Request;
#ifdef  __MigPackStructs
#pragma pack()
#endif
	typedef __Request__Query_async_t __Request;
	typedef __Reply__Query_async_t Reply;

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Request *In1P;
	Reply *OutP = (Reply *) OutHeadP;
	mach_msg_max_trailer_t *TrailerP;
#if	__MigTypeCheck
	unsigned int trailer_size;
#endif	/* __MigTypeCheck */
#ifdef	__MIG_check__Request__Query_async_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__Query_async_t__defined */

	__DeclareRcvSimple(50002, "Query_async")
	__BeforeRcvSimple(50002, "Query_async")

#if	defined(__MIG_check__Request__Query_async_t__defined)
	check_result = __MIG_check__Request__Query_async_t((__Request *)In0P, (__Request **)&In1P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__Query_async_t__defined) */

	TrailerP = (mach_msg_max_trailer_t *)((vm_offset_t)In0P +
		round_msg(In0P->Head.msgh_size));
	if (TrailerP->msgh_trailer_type != MACH_MSG_TRAILER_FORMAT_0)
		{ MIG_RETURN_ERROR(In0P, MIG_TRAILER_ERROR); }
#if	__MigTypeCheck
	trailer_size = TrailerP->msgh_trailer_size -
		(mach_msg_size_t)(sizeof(mach_msg_trailer_type_t) - sizeof(mach_msg_trailer_size_t));
#endif	/* __MigTypeCheck */
#if	__MigTypeCheck
	if (trailer_size < (mach_msg_size_t)sizeof(audit_token_t))
		{ MIG_RETURN_ERROR(OutP, MIG_TRAILER_ERROR); }
	trailer_size -= (mach_msg_size_t)sizeof(audit_token_t);
#endif	/* __MigTypeCheck */
	OutP->RetCode = libinfoDSmig_do_Query_async(In0P->Head.msgh_request_port, In0P->replyToPort.name, In0P->proc, In0P->request, In0P->requestCnt, In1P->callbackAddr, TrailerP->msgh_audit);
	__AfterRcvSimple(50002, "Query_async")
}


#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
boolean_t DSlibinfoMIG_server(
		mach_msg_header_t *InHeadP,
		mach_msg_header_t *OutHeadP);

#ifdef	mig_external
mig_external
#else
extern
#endif	/* mig_external */
mig_routine_t DSlibinfoMIG_server_routine(
		mach_msg_header_t *InHeadP);


/* Description of this subsystem, for use in direct RPC */
const struct libinfoDSmig_do_DSlibinfoMIG_subsystem {
	mig_server_routine_t 	server;	/* Server routine */
	mach_msg_id_t	start;	/* Min routine number */
	mach_msg_id_t	end;	/* Max routine number + 1 */
	unsigned int	maxsize;	/* Max msg size */
	vm_address_t	reserved;	/* Reserved */
	struct routine_descriptor	/*Array of routine descriptors */
		routine[3];
} libinfoDSmig_do_DSlibinfoMIG_subsystem = {
	DSlibinfoMIG_server_routine,
	50000,
	50003,
	(mach_msg_size_t)sizeof(union __ReplyUnion__libinfoDSmig_do_DSlibinfoMIG_subsystem),
	(vm_address_t)0,
	{
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _XGetProcedureNumber, 11, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__GetProcedureNumber_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _XQuery, 16, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__Query_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _XQuery_async, 15, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__Query_async_t)},
	}
};

mig_external boolean_t DSlibinfoMIG_server
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	register mig_routine_t routine;

	OutHeadP->msgh_bits = MACH_MSGH_BITS(MACH_MSGH_BITS_REPLY(InHeadP->msgh_bits), 0);
	OutHeadP->msgh_remote_port = InHeadP->msgh_reply_port;
	/* Minimal size: routine() will update it if different */
	OutHeadP->msgh_size = (mach_msg_size_t)sizeof(mig_reply_error_t);
	OutHeadP->msgh_local_port = MACH_PORT_NULL;
	OutHeadP->msgh_id = InHeadP->msgh_id + 100;

	if ((InHeadP->msgh_id > 50002) || (InHeadP->msgh_id < 50000) ||
	    ((routine = libinfoDSmig_do_DSlibinfoMIG_subsystem.routine[InHeadP->msgh_id - 50000].stub_routine) == 0)) {
		((mig_reply_error_t *)OutHeadP)->NDR = NDR_record;
		((mig_reply_error_t *)OutHeadP)->RetCode = MIG_BAD_ID;
		return FALSE;
	}
	(*routine) (InHeadP, OutHeadP);
	return TRUE;
}

mig_external mig_routine_t DSlibinfoMIG_server_routine
	(mach_msg_header_t *InHeadP)
{
	register int msgh_id;

	msgh_id = InHeadP->msgh_id - 50000;

	if ((msgh_id > 2) || (msgh_id < 0))
		return 0;

	return libinfoDSmig_do_DSlibinfoMIG_subsystem.routine[msgh_id].stub_routine;
}
